### Criar usuário
POST https://chronos-production-f584.up.railway.app/users
Content-Type: application/json

{
  "nome": "O Wagner",
  "email": "OWG@example.com",
  "senha_hash": "senhaSegura123",
  "foto_url": "https://example.com/foto.jpg",
  "ativo": true,
  "score": 1000
}

### Buscar todos os usuários
GET https://chronos-production-f584.up.railway.app/users

### Buscar usuário por ID
GET https://chronos-production-f584.up.railway.app/users/6823804ed7aa7e4e1e34de80

### Atualizar usuário
PATCH https://chronos-production-f584.up.railway.app/users/6812687a03f3a271c0b95dec
Content-Type: application/json

{
  "nome": "João da Silva Atualizado",
  "papel": "Desenvolvedor",
  "score": 92
}

### Associar usuário ao projeto
# Substitua USER_ID e PROJECT_ID pelos IDs reais retornados das requisições acima
POST https://chronos-production-f584.up.railway.app/users/684047d3fbea575cc759e10e/assign-to-project/68404c65fbea575cc759e16e
Content-Type: application/json

{
  "papel": "Desenvolvedor"
}

### Remover usuário
DELETE https://chronos-production-f584.up.railway.app/users/{{userId}}
