// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmAJBjQ1xNjJV4fby3_Kfm4BoII60AFKQ',
    appId: '1:1036037415378:web:42745d5f1a62da6cc1a80b',
    messagingSenderId: '1036037415378',
    projectId: 'chronos-659f7',
    authDomain: 'chronos-659f7.firebaseapp.com',
    storageBucket: 'chronos-659f7.firebasestorage.app',
    measurementId: 'G-SM0MTKPMFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwAlTdjk8VgsFjYovhSiqFG3ZH0CTXL04',
    appId: '1:1036037415378:android:bc62835b89eeeb55c1a80b',
    messagingSenderId: '1036037415378',
    projectId: 'chronos-659f7',
    storageBucket: 'chronos-659f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0PW_IjJpwEE6QrM3SSEbmjU115Cuz36k',
    appId: '1:1036037415378:ios:045055f964ad339ac1a80b',
    messagingSenderId: '1036037415378',
    projectId: 'chronos-659f7',
    storageBucket: 'chronos-659f7.firebasestorage.app',
    iosBundleId: 'com.example.code',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0PW_IjJpwEE6QrM3SSEbmjU115Cuz36k',
    appId: '1:1036037415378:ios:045055f964ad339ac1a80b',
    messagingSenderId: '1036037415378',
    projectId: 'chronos-659f7',
    storageBucket: 'chronos-659f7.firebasestorage.app',
    iosBundleId: 'com.example.code',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmAJBjQ1xNjJV4fby3_Kfm4BoII60AFKQ',
    appId: '1:1036037415378:web:b55bc160f7c6af47c1a80b',
    messagingSenderId: '1036037415378',
    projectId: 'chronos-659f7',
    authDomain: 'chronos-659f7.firebaseapp.com',
    storageBucket: 'chronos-659f7.firebasestorage.app',
    measurementId: 'G-26258GT45E',
  );
}
